services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-ethereum_fetcher}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ethereum-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-ethereum_fetcher}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build:
      context: .
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - API_PORT=3001
      - ETH_NODE_URL=${ETH_NODE_URL:-https://eth-sepolia.g.alchemy.com/v2/YOUR-ALCHEMY-API-KEY}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-ethereum_fetcher}
      - JWT_SECRET='${JWT_SECRET:-your-secret-key}'
      - DB_CONNECTION_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-ethereum_fetcher}
    volumes:
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ethereum-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/lime/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s

networks:
  ethereum-network:
    driver: bridge

volumes:
  postgres_data: 
