import { ApiOperation, ApiResponse } from '@nestjs/swagger';

// Reuse the transaction response schema from eth module
const transactionResponseSchema = {
  type: 'object',
  properties: {
    transactions: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          transactionHash: {
            type: 'string',
            example:
              '0xfc2b3b6db38a51db3b9cb95de29b719de8deb99630626e4b4b99df056ffb7f2e',
            description: 'The hex encoded transaction hash',
          },
          transactionStatus: {
            type: 'number',
            example: 1,
            description:
              'The status of the transaction (1 for success, 0 for failure)',
          },
          blockHash: {
            type: 'string',
            example:
              '0x20c16f757d1fecd1ca00006cb5e10b541b04c70ad0ab3c4cd444f4cd9a0d437b',
            description: 'The hex encoding of the hash of the block',
          },
          blockNumber: {
            type: 'number',
            example: 4553069,
            description: 'The number of the block',
          },
          from: {
            type: 'string',
            example: '0x68ad60cc5e8f3b7cc53beab321cf0e6036962dbc',
            description: 'The ethereum address of the transaction sender',
          },
          to: {
            type: 'string',
            example: null,
            description:
              'The ethereum address of the transaction receiver or null for contract creation',
          },
          contractAddress: {
            type: 'string',
            example: null,
            description:
              'The ethereum address of the newly created contract if this is a contract creation transaction',
          },
          logsCount: {
            type: 'number',
            example: 1,
            description: 'Number of log objects generated by this transaction',
          },
          input: {
            type: 'string',
            example:
              '0x60e060405260008054600160a81b600160e81b031916650a8c0000007d60aa1b179055...',
            description:
              'The hex encoding of the data sent along with the transaction',
          },
          value: {
            type: 'string',
            example: '0',
            description: 'The value transferred in wei',
          },
        },
      },
    },
  },
};

export const getAllTransactionsOperation = ApiOperation({
  summary: 'Get all transactions',
  description: 'Returns a list of all transactions saved in the database',
});

export const getAllTransactionsResponse = ApiResponse({
  status: 200,
  description: 'Successfully retrieved all transactions',
  schema: transactionResponseSchema,
});

export const getAllTransactionsResponse401 = ApiResponse({
  status: 401,
  description: 'Unauthorized - Invalid or missing JWT token',
  schema: {
    type: 'object',
    properties: {
      statusCode: { type: 'number', example: 401 },
      message: { type: 'string', example: 'Unauthorized' },
    },
  },
});

export const getAllTransactionsResponse500 = ApiResponse({
  status: 500,
  description: 'Internal server error',
  schema: {
    type: 'object',
    properties: {
      statusCode: { type: 'number', example: 500 },
      message: { type: 'string', example: 'Failed to retrieve transactions' },
    },
  },
});
